Added send logo
pagopa/pn-downtime-logs pull request #127
Opened 2023-06-07 16:18 UTC by angelaantoniaceaa

2023-06-08 15:11 UTC, MTurraPpa requested changes

2023-06-08 15:11 UTC, MTurraPpa commented on pom.xml
> +		</openapi-generator-maven-plugin-version>
Attenzione alla formattazione

2023-06-09 08:15 UTC, angelaantoniaceaa commented on pom.xml
> +		<version>2.0.1-SNAPSHOT</version>
Perché pn-parent presenta la versione **2.0.1-SNAPSHOT** sul pom.xml [https://github.com/pagopa/pn-parent/blob/develop/pom.xml](https://github.com/pagopa/pn-parent/blob/develop/pom.xml)  su develop. Quindi localmente fallisce la build se lascio la versione 2.0.0. Posso chiederti da dove downtime recupera le versioni?

2023-06-09 08:16 UTC, angelaantoniaceaa commented on pom.xml
> +			<version>2.1.0-SNAPSHOT</version>
Anche in questo caso pn-commons presenta la versione **2.1.0-SNAPSHOT** sul pom.xml, quindi localmente fallisce la build se lascio la versione 2.0.0

2023-06-13 07:55 UTC, MTurraPpa commented on pom.xml
> +		<version>2.0.1-SNAPSHOT</version>
Ci sono due modi:

1. Scaricare un locale il tag v2.0.0 e eseguire mvn install
2. Configurare il repo di CodeArtifact dell'ambiente cicd (vedi https://pagopa.atlassian.net/wiki/spaces/PN/pages/575768846/Configurazione+CodeArtifact+per+compilazione+maven+in+locale)

2023-06-13 09:47 UTC, MTurraPpa approved these changes

2023-06-13 10:22 UTC, merged